### ISSUE TITLE
control-nav displaying below just in Safari

### ISSUE THREAD

**Issue by JMarqz** [woocommerce/FlexSlider#1375]
I've been using Flexslider for some sites and I didn't realize that control-nav is displayed below than normal just in Safari. I realized because in a project I was needing perfect alignment cross-browser. I tested in Chrome, Opera and Firefox, all with the expected behavior except for Safari.

My control nav was styled:

``` css
.mariano-galeria .flex-control-paging li a {
    width: 30px;
    height: 6px;
    background: #666;
    background: rgba(0, 0, 0, 0.2);
    border-radius: 0px;
    box-shadow: none;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
}

.mariano-galeria .flex-control-nav {
    height: 6px;
    max-width: 100%;
    right: 0;
    left: 0;
    margin: auto;
    bottom: 4px;
}
```

I asked for help in a <a href="http://stackoverflow.com/questions/31214536/flexslider-control-nav-displaying-below-than-normal-css-instructions-just-in-saf" target="_blank">SO Question</a> and a solution for me was adding a `line-height: 0` to the `.flex-control-nav` class.

This make sense to me since Flexslider insert numbers in the `flex-control-nav` list and "disappear it" with `text-indent: -9999px`.

I guess I'm not the only one with this problem, so I decided publish it here to let know about this bug and share what works for me. Maybe you could fix it in new versions.
