### ISSUE TITLE
Control nav doesn't show until after first transition on IE8

### ISSUE THREAD

**Issue by epavletic** [woocommerce/FlexSlider#161]
Implemented this for a client yesterday, and it seems to work exactly as I want on all browsers that I want to support except IE8, where the .flex-control-nav-list doesn't get visible until after the first transition. I've tried to figure out what's causing this, but to no avail. Since IE developer tools doesn't show dynamic content I can't confirm that the control nav is rendered on page load, or if they get created when the first transition occur.

js:

``` javascript
 $('.view-Slideshow').flexslider({
      directionNav: false
    });
```

css:

``` css
.view-Slideshow {
  position: relative;
}

.flex-control-nav {
  position: absolute;
  right: 30px;
  bottom: 0;
  list-style: none;
  z-index: 99999999999999999999;  /* awesome debugging */
  zoom: 1;
}

.flex-control-nav li {
  float: left;
  margin-left: 5px;
}

.flex-control-nav a {
  background: url(../images/slideshow-controls.png) no-repeat right top;
  display: block;
  text-indent: 100%;
  white-space: nowrap;
  width: 13px;
  overflow: hidden;
}
```
