### ISSUE TITLE
flexslider.css missing -moz-transition

### ISSUE THREAD

**Issue by ArnaudBan** [woocommerce/FlexSlider#263]
I added `-moz-transition: all .3s ease;` at the end of line 52 so that it look nice in mozilla

``` css
.flex-direction-nav a {
    width: 30px; 
    height: 30px; 
    margin: -20px 0 0; 
    display: block;
    background: url(images/bg_direction_nav.png) no-repeat 0 0; 
    position: absolute; 
    top: 50%; 
    cursor: pointer;
    text-indent: -9999px; 
    opacity: 0; 
    -webkit-transition: all .3s ease;
    -moz-transition: all .3s ease;
}
```

I think it would be nice to also add
`-o-transition: all .3s ease;` and `transition: all .3s ease;`
