### ISSUE TITLE
Changing pagination bubbles with multiple sliders

### ISSUE THREAD

**Issue by barchard** [woocommerce/FlexSlider#95]
Hi-

How do you recommend changing the pagination bubbles with multiple sliders on a page?

This works, but would apply to all sliders on a page:

``` html
<div id="flex-control-nav-container-1" class="flex-control-nav-container"></div>
```

``` css
.flex-control-nav li a {width: 13px; height: 13px; display: block; background: url(bg_control_nav_blue.png) no-repeat; cursor: pointer; text-indent: -999em;}
```

This, however, only shows the 'empty' bubbles that do not animate to active:

``` css
#flex-control-nav-container-1 .flex-control-nav li a {width: 13px; height: 13px; display: block; background: url(bg_control_nav_blue.png) no-repeat; cursor: pointer; text-indent: -999em;}
```

Thanks
Greg
